name: Build & Submit to Play Store

on:
  push:
    tags: ["v*"]

jobs:
  build_android:
    name: Build Android production
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit to Play Store
    needs: [build_android]
    type: submit
    params:
      platform: android
      profile: production
      build_id: ${{ needs.build_android.outputs.build_id }}
